# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 01:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willgo_name', models.CharField(max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=120)),
                ('company_zip', models.CharField(max_length=13)),
                ('company_address', models.CharField(max_length=120)),
                ('company_address2', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
                ('company_tel', models.CharField(max_length=32)),
                ('is_filled', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
