# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('trial_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('f', 'FREE'), ('p', 'PAYING')], default='f', max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='basicinfo',
            old_name='update_date',
            new_name='updated_date',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='company_tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Plan'),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
