# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160615_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='plan',
            field=models.CharField(choices=[('f', 'FREE'), ('p', 'PAYING')], default='f', max_length=12),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
