# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160615_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=12)),
            ],
        ),
    ]
