# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_businessday'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='business_days',
            field=models.ManyToManyField(to='dashboard.BusinessDay'),
        ),
    ]
