# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_basicinfo_business_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.CharField(choices=[('M', '月'), ('T', '火'), ('W', '水')], max_length=3),
        ),
    ]
