# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160615_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessday',
            name='day',
            field=models.CharField(choices=[('MON', '月'), ('TUE', '火'), ('WED', '水'), ('THU', '木'), ('FRI', '金'), ('SAT', '土'), ('SUN', '日')], max_length=3),
        ),
    ]
